# Generated by Django 4.1.4 on 2023-01-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
